### ISSUE TITLE
ERC721 metadata

### ISSUE THREAD

**Issue by utgarda** [NotarizedScreenshot/external-adapter#2]
Metadata apart from the common
```
image
name
description
```
fields should contain a non-nested list of fields to be displayed by OpenSea, which is not the case at the moment

https://opensea.io/assets/matic/0xa567349bdd3d4f2c3e25f65745a020162c202ef2/84307257459994798809780116847464305561807004997505001778221767653301679369311

https://ipfs.io/ipfs/bafkreiagptjneiv6dndjelhsogyjfiw4b4pl6ijqzvksiqr2hnbbk4m3am

![Image](https://user-images.githubusercontent.com/15115/180599187-bcb0f070-f26b-4a9a-80be-8ac949ac862e.png)

**Comment by vicglarson** [comment]
https://github.com/NotarizedScreenshot/external-adapter/commit/acc72195ab91779c86d34865e6abb5a6fbc4476b
