### ISSUE TITLE
Allow a user to send request with both URL and Tweed ID

### ISSUE THREAD

**Issue by poludnev** [NotarizedScreenshot/external-adapter#36]
Change "url" in the request body to "tweeId". It should be changed in the chainlink node request respectively.

It is more convenient to copy-past the whole URL instead of tweet ID.

The question largely concerns frontend, but two repositories cannot be attached to one task, so I will duplicate it for frontend as well.

Initially, both on the frontend and adapter, we accepted a URL from the user. Later, we decided to change it to a tweet ID.

From a user experience standpoint, there is an issue:

If the user wants to save a tweet from the web interface, then they will have to copy the tweet ID from the address bar.

This is not very convenient; it is much easier to copy the entire address, so as not to aim at the numbers, accidentally catch a slash, or miss a required digit.

Therefore, I suggest accepting both the tweet address and the ID separately. Both can be validated.

The browser extension will continue to send the tweet ID.

**Comment by poludnev** [comment]
Вопрос касается в значительной степени и фронтенда, но нельзя приделать два репозитория к одной задаче, поэтому продублирую и для фронта. 

Изначально как на фронте, так и на адаптере, мы принимали от пользователя  url. Впоследствии, решили изменить его на tweet id.

С точки зрения user experience есть такая проблема: 

Если пользователь захочет сохранить твит из веб-интерфейса:


![Image](https://user-images.githubusercontent.com/51874367/228305701-bc747d85-6c82-451b-93ce-480a6f1fc347.png)


 то ему придется скопировать tweet id из адресной строки:


![Image](https://user-images.githubusercontent.com/51874367/228305855-e89a9721-9b14-4fa1-97c1-c35be66162dd.png)

Это не очень удобно, гораздо проще скопировать адрес целиком, чтобы не прицеливаться в цифры, не цеплять случайно слэш или наоборот не скопировать нужную цифру. 

Поэтому предлагаю принимать как адрес твита, так и айди отдельно. Валидировать можно и то, и другое. 

Браузерное расширение будет попрежнему  отправлять  tweet id.

**Comment by utgarda** [comment]
Let's accept `tweetId`s as well as complete tweet URLs, validate both on the frontend and only extract and send `tweetId` in http requests to preview generators and Chainlink node adapters.

**Comment by poludnev** [comment]
Noted. 
Same task for frontend to keep tracked: 
https://github.com/NotarizedScreenshot/notaryshot-frontend/issues/96

**Comment by poludnev** [comment]
Decide to handle only tweet id on frontend. Close this task, proceed with the same for front repo.
